### ISSUE TITLE
Add JSON buttons to messages

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Trumpet#1]
Button would look like this:

```
[Click me]
```

And would be appended at the end of a message, with a single space before it.

Two colors can be defined globally, one for brackets, other for text label inside.

Button definitions can be created in config:

``` yaml
Buttons:
  reddit-flatcore:
    label: /r/flatcore
    hover:
    - '&7Click to visit our subreddit'
    - ‘&8Make sure to subscribe!’
    action: http://www.reddit.com/r/flatcore
```
1. `label` doesn’t accept formatting codes
2. If `action` doesn’t begin with a slash, it’s a web address
3. Buttons are referenced in messages through `<button-name>` variable. Example: `<reddit-flatcore>`
